# Generated by Django 6.0.4 on 2026-06-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('pengarang', models.CharField(max_length=255)),
                ('kategori', models.CharField(blank=True, max_length=100)),
                ('penerbit', models.CharField(blank=True, max_length=100)),
                ('tahun_terbit', models.IntegerField(blank=True, null=True)),
                ('rak', models.CharField(blank=True, max_length=50)),
                ('stok', models.IntegerField(default=0)),
                ('deskripsi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Buku',
                'verbose_name_plural': 'Buku',
                'db_table': 'buku',
            },
        ),
    ]
